### ISSUE TITLE
Redimension des images

### ISSUE THREAD

**Issue by fg1989** [gen-classroom/projet-grindelwald#23]
Ecrire une fonction qui prend en paramètre le chemin vers une image et une taille et qui génère une image a la taille indiquée.

La taille sera fourni sous forme d'énum qui décrira le medium sur lequel l'image sera affichée (e.g. natel avec DPI normal, natel 4k, tablette normal, tablette ipad, PC 14", Taille originale).

Chercher librairie Java (imagemagik) pour les résolutions des images : La résolution de l'image sera adaptée au type de support du client (https://imagemagick.org/script/develop.php)

**Comment by roosemberth** [comment]
Il a été décidé de réorienter les objectifs du développement et cet issue n'est
plus une priorité. Pour plus d'informations, voir le PV du 22.04.21.

/close
